config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks", confirmations: 'confirmations' }
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    get 'events/new'
    get 'events/show'
    root to: 'pages#index'
    get 'pages/index'
    get 'pages/show'
    get '/pages/show_old', to: 'pages#show_old'
    get '/users/search', to: 'users#search'
    get '/users/lang', to: 'users#lang'
    post '/users/follow', to:'users#follow'
    resources :events
    resources :posts
    post '/users/approve', to: 'users#approve'
    post '/users/unfollow', to: 'users#unfollow'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/views/pages/_calendar.html.erb
<h2><%= image_tag('calendar.png', :size => "32x32") %> CALENDAR <%= image_tag('calendar.png', :size => "28x28") %> </h2> 
<%= month_calendar do |date| %>
    <center>
    <% if has_event?(date) %>
        <div class="tooltip1">
            <div class="description1">
                <% for daily_event in events_at_day(date) do %>
                    <%= daily_event[:name] + "(" + daily_event[:time] + "~)" %><br>
                <% end %>
            </div>
                <b><font color="red"><%= date.day %></color></b>
        </div>
    <% else %>
        <%= date.day %>
    <% end %>
    </center>
<% end %>   

app/views/pages/_event_list.html.erb
<div class="roundbox">
    <div id="event_title">
        <%= link_to(event.name, event_path(event.id)) %>
    </div>
    <div id="event_time">
        <%= I18n.t("pages.start_time") %>:<%= event.start_time.strftime("%Y/%m/%d %H:%M").to_s %><br>
        <%= I18n.t("pages.end_time") %>:<%= event.end_time.strftime("%Y/%m/%d %H:%M").to_s %>
    </div>
    <div>
    <% admin_user = User.find_by(id: event.user_id) %>
    <%= render partial: 'users/user_mini_image', locals: {usr: admin_user} %>
    <% event.participants.each do |participants| %>
          <% user = User.find_by(id: participants.user_id) %>
          <%= render partial: 'users/user_mini_image', locals: {usr: user} %>
    <% end %>
    </div>
    <div id="event_edit">
        <% if event.user_id == current_user.id %>
            <%= link_to(I18n.t("common.edit"), edit_event_path(event.id)) %>
            　　
            <%= link_to(I18n.t("common.delete"), event, :method => :delete, 
            title: event.name, 
            data: { confirm: I18n.t("pages.confirm"),
            commit: I18n.t("pages.commit"),
            cancel: I18n.t("common.cancel") 
        } ) %>
        <% end %>
    </div>

</div>

app/views/pages/_folloer.html.erb
<% @followers.each do |friend| %>
    <%= image_tag "#{friend.profile_image_url}" %>
    <a href="https://twitter.com/<%= friend.screen_name %>" target="_blank"><%= friend.name %></a>
    @<%= friend.screen_name %>
    <hr>
<% end %>

app/views/pages/index.html.erb
<ul>
<% if user_signed_in? %>
  <li><%= link_to I18n.t("pages.logout"), destroy_user_session_path, method: :delete %></li>
<% else %>
  <li><%= link_to I18n.t("pages.login"), user_twitter_omniauth_authorize_path %></li>
<% end %>
</ul>

app/views/pages/show.html.erb
<div class="page-container">
    <div class="event-list">
    <center>
        <div class="admin_info">
        <h1>INFOMATION</h1>
        <hr>
        <% @info.each do |info| %>
            [<%= info.updated_at.year %>/<%= info.updated_at.month %>/<%= info.updated_at.day %>更新] 
            <%= info.title %>
            <br>
        <% end %>
        </div>
    </center>

        <center>
            <div id="event_top">
                <h2>RECENT EVENTS</h2>
            </div>
            <!-- すべてのイベントの中から現在のユーザが作成したものを表示する -->
                <% @events.each do |event| %>
                    <%= render partial: 'event_list', locals: {event: event} %>
                <% end %>
                <%= paginate(@events) %>
            <hr>
            <%= link_to I18n.t("pages.old"), pages_show_old_path %>
            <br>
            <%= link_to I18n.t("pages.new"), new_event_path %>
        </center>
    </div>

    <div class="user-info">
        <center>
            <h2><%= image_tag('profile.png', :size => "32x32") %> YOUR IMAGE <%= image_tag('profile.png', :size => "32x32") %> </h2>
                <%= render partial: 'users/user_image', locals: {usr: current_user} %>
            <br>
            <% if current_user.try(:admin?) %>
                <%= I18n.t("pages.admin_user") %>
            <% else %>
                <%= I18n.t("pages.normal_user") %>
            <% end %>
            <%= render 'calendar' %>
            <h2><%= image_tag('friends.png', :size => "32x32") %> FRIENDS <%= image_tag('friends.png', :size => "32x32") %></h2>
            <br>
            <%= render '/users/friend_list' %>
            <%= form_tag("/users/search",:method => 'get', class: "search_form") do %>
                <%= text_field_tag :search %>
                <%= submit_tag I18n.t("common.search"), :name => nil %>
            <% end %>
        </center>
    </div>
</div>

app/views/pages/show_old.html.erb
<div class="event-list">
    <center>
        <div id="event_top">
            <h2>OLD EVENTS</h2>
        </div>
        <!-- すべてのイベントの中から現在のユーザが作成したものを表示する -->
            <% @events.each do |event| %>
                <%= render partial: 'event_list', locals: {event: event} %>
            <% end %>
            <%= paginate(@events) %>
        <hr>
        <%= link_to I18n.t("pages.recent"), pages_show_path %>
        <br>
        <%= link_to I18n.t("pages.new"), pages_show_old_path %>
    </center>
</div>