config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks", confirmations: 'confirmations' }
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    get 'events/new'
    get 'events/show'
    root to: 'pages#index'
    get 'pages/index'
    get 'pages/show'
    get '/pages/show_old', to: 'pages#show_old'
    get '/users/search', to: 'users#search'
    get '/users/lang', to: 'users#lang'
    post '/users/follow', to:'users#follow'
    resources :events
    resources :posts
    post '/users/approve', to: 'users#approve'
    post '/users/unfollow', to: 'users#unfollow'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/views/layouts/_droplist.html.erb
<%= image_tag('edit.png') %>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SETTINGS<span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href=<%= edit_user_registration_path %>>EDIT PROFILE</a></li>
        <li role="separator" class="divider"></li>
        <% if locale == :en %>
        <%= link_to('言語設定を日本語に変更', users_lang_path(lang: 'japanise')) %>
        <% else %>
        <%= link_to('Change To English', users_lang_path(lang: 'english')) %>
        <% end %>
    </ul>
</li>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <%= favicon_link_tag 'favicon.ico' %>
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <div class="nav_menu">
              <div class="nav_element">
                <%= render partial: 'layouts/navi', locals: {image_name: 'home.png', link_name: 'HOME', link_path_name: pages_show_path, method: :get} %>
              </div>
              <div class="nav_element">
                <%= render partial: 'layouts/navi', locals: {image_name: 'new.png', link_name: 'NEW', link_path_name: events_new_path, method: :get} %>
              </div>
              <div class="nav_element">
                <%= render partial: 'layouts/droplist' %>
              </div>
              <div class="nav_element">
                <%= render partial: 'layouts/navi', locals: {image_name: 'logout.png', link_name: 'LOGOUT', link_path_name: destroy_user_session_path, method: :delete} %>
              </div>
            </div>
            <% else %>
              <%= render partial: 'layouts/navi', locals: {image_name: 'signup.png', link_name: 'SIGNUP', link_path_name: new_user_registration_path, method: :get} %>
              <%= render partial: 'layouts/navi', locals: {image_name: 'login.png', link_name: 'LOGIN', link_path_name: new_user_session_path, method: :get} %>
              <% end %>
          </ul>  
        </nav>    
      </div>    
    </header>

app/views/layouts/_navi.html.erb
<%= image_tag(image_name) %>
<%= link_to link_name, link_path_name, method: method %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoteiApp</title>
    <%= include_gon %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>

    <meta name="viewport" content="width=device-width,
                          initial-scale=1.0,
                          minimum-scale=1.0",
                          user-scalable=no>
  </head>

  <body>
    <%= render '/layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>